# Generated by Django 5.1.5 on 2025-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgis', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='resources/pdfs/')),
                ('icon_class', models.CharField(default='fas fa-file-pdf', max_length=50)),
            ],
        ),
    ]
