# Generated by Django 5.1.5 on 2025-02-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgis', '0005_counselingrequest_financialaidrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselingRequest',
        ),
        migrations.DeleteModel(
            name='FinancialAidRequest',
        ),
        migrations.DeleteModel(
            name='StudentAffairsInquiry',
        ),
    ]
